
#MeSS parameters
replicates: 1

community_name: 'CF_metagenome'

proportion_reads: {'virus':0.01,'human':0.9,'bacteria':0.08,'non_human_eukaryotes':0.01}

illumina_sequencing_system: 'HSXt'#HiSeqX TruSeq (read length:150bp)

total_amount_reads: 10000000 #10 mil reads in total

read_length: 150

mean_fragment_length: 200

sd_fragment_length: 10

read_status: 'paired'

sd_read_num: 0 #Standard deviation for varying the number of reads per replicate, if 0 keep the same number of reads for each replicate


#Assembly finder config

input_table_path: path/to/input_table

NCBI_key: your_ncbi_api_key

NCBI_email: your_ncbi_email

##Parameters for search_assemblies function
#This set of parameters is to search all possible assemblies excluding ones from metagenomes
complete_assemblies: False

reference_assemblies: False

representative_assemblies: False

exclude_from_metagenomes: True

Genbank_assemblies: True

Refseq_assemblies: True

##Parameters for the filtering function
Rank_to_filter_by: 'None'
#None: Assemblies are ranked by their assembly status (complete or not)
#and Refseq category (reference, representative ...)
#If you want to filter by species, set this parameter to 'species'. The filtering function will list all unique species
#and rank their assemblies according to assembly status and Refseq category.

assembly_finder_Snakefile: path/to/assembly_finder/Snakefile