#MeSS parameters
replicates: 1 #You con set the number of times to simulate the same metagenome
community_name: CF-metagenome
assemblies_dir: /absolute/path/to/assemblies

#Distribution params
dist: lognormal
mu: 1
sigma: 0
#Sequencing run params
seq_tech: illumina #[illumina, pacbio, nanopore]
read_status: paired #set to single for single read simulation or longread simulation
total_reads: 10000000 #10 mil reads in total.
                      #If the user inputs coverage values in input_table.tsv, then this value will not be used
##Illumina (art params)
illumina_sequencing_system: HSXt #HiSeqX TruSeq (read length:150bp)
illumina_read_len: 150
illumina_mean_frag_len: 200
illumina_sd_frag_len: 10
bam: False
##Long reads (pbsim2 params)
chemistry: R94 #Select R94, R95, R103 pore versions for Nanopore.
                #Select P4C2, P5C3, P6C4 chemistry for PacBio
longreads_min_len: 100
longreads_max_len: 1000000
longreads_sd_len: 7000
longreads_mean_len: 9000
longreads_mean_acc: 85
difference_ratio: "23:31:46" #Rate of substitution:insertion:deletion.
                          #For PacBio the default values is 6:50:54
                          #For Nanopore it is 23:31:46
##Replicate params
sd_rep: 0 #Standard deviation for varying the number of reads per genome between replicates,
              #if 0 keep the same number of reads per genome for each replicate
              #else vary the read number between replicates by sampling from a normal distribution
seed: 1 #Set this parameter to a fixed number so data from random number generators is reproducible

#Assembly finder parameters
input_table_path: path/to/input_table
NCBI_key: your_ncbi_api_key
NCBI_email: your_ncbi_email

##Parameters for search_assemblies function
#This set of parameters is to search all possible assemblies excluding ones from metagenomes
complete_assemblies: False
reference_assemblies: False
representative_assemblies: False
exclude_from_metagenomes: True
Genbank_assemblies: True
Refseq_assemblies: True

##Parameters for the filtering function
Rank_to_filter_by: 'None'
#None: Assemblies are ranked by their assembly status (complete or not)
#and Refseq category (reference, representative ...)
#If you want to filter by species, set this parameter to 'species'. The filtering function will list all unique species
#and rank their assemblies according to assembly status and Refseq category.
