
#Paramters to be inputted by the user

NCBI_key: '7308cc05fae74fc2be841860d3ab0e5abe09'

NCBI_email: 'farid.chaabane@unil.ch'

input_table: '/home/master_students/2019_Farid/SRS_test/input_table.tsv'

pipeline_path: '/home/master_students/2019_Farid/SRS'

proportion_reads: {'virus':0.01,'human':0.9,'bacteria':0.08,'non_human_eukaryotes':0.01}

illumina_sequencing_system: 'HSXt'#HiSeqX TruSeq (read length:150bp)

total_amount_reads: 10000000 #10 mil reads in total

read_length: 150

mean_fragment_length: 200

sd_fragment_length: 10

read_status: 'paired'

shuffling_seed: 42