
#Paramters to be inputted by the user

NCBI_key: '7308cc05fae74fc2be841860d3ab0e5abe09'

NCBI_email: 'farid.chaabane@unil.ch'

input_table: '/home/master_students/2019_Farid/SRS_test/input_table.tsv'

proportion_reads: {'virus':0.01,'human':0.9,'bacteria':0.09}

illumina_sequencing_system: 'HSXt'#HiSeqX TruSeq (read length:150bp)

total_amount_reads: 10000000 #10 mil reads in total

read_length: 150


