site_name: MeSS
repo_name: metagenlab/mess
repo_url: https://github.com/metagenlab/MeSS
site_author: Farid Chaabane
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true


nav:
  - Home: index.md
  - Motivation: motivation.md
  - Citation: citation.md
  - Getting started:
      - Install: install.md
      - Step by step guide:
        - 1) Setup inputs: guide/input.md
        - 2) Download genomes <small>(optional)</small>: guide/download.md
        - 3) Community design: guide/community.md
        - 4) Fasta/reads processing: guide/processing.md
        - 5) Output: output.md
  - Commands:
      - download: commands/download.md
      - simulate: commands/simulate.md
      - run: commands/run.md
      - hmp-template: commands/hmp-template.md
  - Tutorials:
      - Run the test command: tutorials/test.md
      - Run using a taxonomic profile: 
        - Bracken: tutorials/bracken.md
  - Benchmarks:
      - benchmarks/index.md
      - Species composition: benchmarks/species-composition.md
      - Resource usage: benchmarks/resource-usage.md
