site_name: MeSS
site_url: "https://github.com/metagenlab/MeSS"
site_author: Farid Chaabane
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - bash
    - shell
    - python
nav:
  - ABOUT:
      - Overview: index.md
      - Motivation: motivation.md
      - Citation: citation.md
  - RUNNING:
      - Install: install.md
      - Input: input.md
      - Usage: run.md
      - Examples: examples.md
  - OUTPUT:
      - Output: output.md
  - APPLICATIONS:
      - Applications: applications.md
  - BENCHMARKING:
      - Benchmarking: benchmarking.md
