site_name: MeSS
repo_name: metagenlab/mess
repo_url: https://github.com/metagenlab/MeSS
site_author: Farid Chaabane
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home:
      - Overview: index.md
      - Motivation: applications.md
      - Citation: citation.md
  - Getting started:
      - Install: install.md
      - Run: run.md
      - Input: input.md
      - Output: output.md
  - Tutorials:
      - Examples: examples.md
  - Benchmarks:
      - Benchmarking: benchmarking.md
