"""
Snakefile for downloading genomes and simulating reads
"""


include: os.path.join("download.smk")
include: os.path.join("simulate.smk")


rule all:
    input:
        TargetDownloads,
        TargetSimreads,
