# Namespaced config file example
resources:
  big:
    mem: 32000
    cpu: 16
    time: "23:00:00"
  med:
    mem: 16000
    cpu: 8
    time: "08:00:00"
  norm:
    mem: 6000
    cpu: 3
    time: "00:30:00"
  sml:
    mem: 2000
    cpu: 1
    time: "00:01:00"
