args:
  accuracy: 
  annotated: 
  api_key: 
  asm_summary: 
  assembly_level: 
  atypical: 
  bam: 
  bases: 
  compressed: 
  configfile: 
  custom_err: 
  dist: 
  error:
  errfree: 
  fasta: 
  frag_len: 
  frag_sd: 
  include: 
  input: 
  limit: 
  log: 
  mag: 
  max_len: 
  mean_len: 
  min_len: 
  model: 
  model_path: 
  mu: 
  nrank: 
  output: 
  paired: 
  passes: 
  prefix: 
  profile: 
  rank: 
  ranks: 
  ratio: 
  reference: 
  rep_sd: 
  replicates: 
  sd_len: 
  sdm: 
  seed: 
  sigma: 
  skip_shuffle: 
  snake_args: 
  snake_default:
  source:
  system_config: 
  taxon: 
  taxonkit: 
  tech: 
  threads: 
  tool: 

resources:
  big:
    cpu: 16
    mem: 32000
    time: "23:00:00"
  med:
    cpu: 8
    mem: 16000
    time: "08:00:00"
  norm:
    cpu: 4
    mem: 4000
    time: "00:30:00"
  sml:
    cpu: 1
    mem: 2000
    time: "00:00:10"
