name: Tests

on:
  push:
    branches: [main, dev]
    paths:
      - ".github/workflows/unit-tests.yml"
      - "tests/**"
      - "mess/**"
      - "setup.py"
      - "!.github/workflows/build-docs.yml"
      - "!docs/**"
      - "!mkdocs.yml"

permissions:
  contents: read

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MeSS environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: mess
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true

      - name: Setup apt dependencies
        run: |
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt install -y squashfuse fuse2fs gocryptfs apptainer

      - name: Disable apparmor namespace restrictions for apptainer
        run: |
          sudo sh -c 'echo kernel.apparmor_restrict_unprivileged_userns=0 \
              >/etc/sysctl.d/90-disable-userns-restrictions.conf'
          sudo sysctl -p /etc/sysctl.d/90-disable-userns-restrictions.conf

      - name: Install MeSS and pytest-cov
        run: |
          pip install -e .
          pip install pytest coverage

      - name: Run tests on ${{ matrix.os }} for python ${{ matrix.python-version }}
        run: |
          coverage run -m pytest
