name: Tests

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/unit-tests.yaml"
      - "tests/**"
      - "mess/**"
      - "setup.py"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/unit-tests.yaml"
      - "tests/**"
      - "mess/**"
      - "setup.py"

permissions:
  contents: read

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-version: "latest"
          miniforge-variant: Mambaforge
          use-mamba: true
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          channel-priority: strict
          activate-environment: mess
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: "Test and generate coverage report on ${{ matrix.os }} for Python ${{ matrix.python-version }}"
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage
          python -m pip install .
          coverage run -m pytest
