name: Tests

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/unit-tests.yml"
      - "tests/**"
      - "mess/**"
      - "setup.py"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/unit-tests.yml"
      - "tests/**"
      - "mess/**"
      - "setup.py"

permissions:
  contents: read

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: Setup apptainer
        uses: eWaterCycle/setup-apptainer@v2.0.0

      - name: "Test and generate coverage report on ${{ matrix.os }} for Python ${{ matrix.python-version }}"
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage
          python -m pip install .
          coverage run -m pytest
